- Open-Shift/Open-Shift.csproj
- Open-Shift/Properties/AssemblyInfo.cs
Fixed broken file references in Open-Shift.csproj and commented line in AssemblyInfo.cs
> Fixed broken file references in Open-Shift.csproj and fixed bug

- Open-Shift/Models/Database.cs
- Open-Shift/Views/Profile/Index.cshtml
- Open-Shift/Web.config
I believe this should be the proper connection setup for the .mdf
> Added connectionString to web.config

- Open-Shift/Models/Database.cs
- Open-Shift/Models/User.cs
*added inser_user and update_user stored procedures
*updated user references to include manager and status
*changed parameters in database.cs to reflect stored procedure
> added insert_user and update_user stored procedures

- Open-Shift/NOTES.txt
- Open-Shift/Open-Shift.csproj
- Open-Shift/Web.config
Started learning .NET MVC, made a file with notes to share. I highly recommend watching that complete tutorial video and reading all the notes in NOTES.txt
> Started learning .NET MVC, made a file with notes to share

- Open-Shift/App_Log/sys_log.xls
- Open-Shift/Models/SysLog.cs
- Open-Shift/Web.config
added a variable to SysLog.cs and removed absolute path call in web.config. Should now work for all of us
> Adding relative path to log file

- Open-Shift/DatabaseDocumentation.txt
* These are all the stored procedures I have on my list to make.
* They may need some modification
* Adding Documentation
> Adding stored procedures & database documentation

- Open-Shift/Database_Documentation.txt
more database changes
*changed insert_shift to create_shift
*added delete_shift
* added update_shift
* updated documentation
> adding more stored procs for scheduling

- Open-Shift/Controllers/HomeController.cs
- Open-Shift/Controllers/Profile.cs
- Open-Shift/Models/Database.cs
- Open-Shift/Models/Home.cs
- Open-Shift/Models/SystemList.cs
- Open-Shift/Models/User.cs
- Open-Shift/Open-Shift.csproj
- Open-Shift/Views/Profile/Index.cshtml
- Open-Shift/Views/Profile/SignIn.cshtml
- Open-Shift/Views/Profile/SignUp.cshtml
- Open-Shift/Views/Profile/Update.cshtml
Have some work on do on the css. Some pages are off. Working on sign in and Main Page now
> SignUp works

- Open-Shift/App_Log/sys_log.xls
- Open-Shift/Models/SysLog.cs
- Open-Shift/Open-Shift.csproj
Error log somehow stopped working. Just fixed it
> Fixing Error Log

- Open-Shift/App_Log/sys_log.xls
- Open-Shift/Controllers/Profile.cs
- Open-Shift/Models/Database.cs
- Open-Shift/Models/SystemList.cs
- Open-Shift/Models/User.cs
- Open-Shift/Views/Profile/Index.cshtml
- Open-Shift/Views/Profile/SignUp.cshtml
- Open-Shift/Views/Profile/Update.cshtml
> Signup/SignIn is WORKING!!

- Open-Shift/Models/User.cs
- Open-Shift/Views/Profile/SignUp.cshtml
Let me know if you see something I missed.
> Adding validation

- .gitignore
- Open-Shift/Models/Database.cs
- Open-Shift/Views/Profile/Update.cshtml
Changed proc
blnIsManager is coming back as false in a model when it should be 0 or 1
Unsure about whether statusID or StoreID are working correctly but everything above those have the right info in the variable
> Login changes

- Open-Shift/Models/Database.cs
- Open-Shift/Models/User.cs
Fixed StatusId, StoreId and IsManager which will now properly insert correct values
> Fixed Inserts for signup

- .gitignore
- Open-Shift/App_Log/sys_log.xls
- Open-Shift/Database_Documentation.txt
- Open-Shift/Open-Shift.csproj.user
- Open-Shift/Views/Profile/SignUp.cshtml
*added get_shift_store_month_year
*added type=clear to clear button
> adding shift stored proc

- Open-Shift/App_Log/sys_log.xls
- Open-Shift/Controllers/AvailabilityController.cs
- Open-Shift/Models/Availability.cs
- Open-Shift/Models/Database.cs
- Open-Shift/Scripts/calendar.js
Finished allowing users to create and view their availabilities
> Finished allowing users to create and view their availabilities

- Open-Shift/Controllers/EmailController.cs
- Open-Shift/Controllers/Profile.cs
- Open-Shift/Open-Shift.csproj
- Open-Shift/Web.config
Email is sent on user signup. I've commented out text for now
> Adding Email Functionality

- Open-Shift/Controllers/AvailabilityController.cs
- Open-Shift/Models/Availability.cs
- Open-Shift/Models/Database.cs
- Open-Shift/Scripts/calendar.js
- Open-Shift/Scripts/database.js
- Open-Shift/Scripts/dom-elements.js
Finished allowing users to delete their availabilities
> Finished allowing users to delete their availabilities

- Open-Shift/Controllers/Profile.cs
- Open-Shift/Views/Profile/SignUp.cshtml
- Open-Shift/Views/Profile/Update.cshtml
*also working on cancel buttons
> Added UPDATE_AVAILABILITY

- Open-Shift/Models/SystemList.cs
- Open-Shift/Views/Profile/Update.cshtml
> Fixing update to show content of DDLs

- Open-Shift/App_Log/sys_log.xls
- Open-Shift/Controllers/Profile.cs
- Open-Shift/Models/Database.cs
- Open-Shift/Models/User.cs
- Open-Shift/Views/Profile/ResetPassword.cshtml
if (col["btnCancel"] == "cancel") return RedirectToAction("SignIn", "Profile");
if (col["btnClear"] == "clear") return RedirectToAction("SignUp", "Profile");
> SignUp - Cancel/Clear

- Open-Shift/App_Log/sys_log.xls
- Open-Shift/Controllers/EmailController.cs
- Open-Shift/Views/Profile/Update.cshtml
Annie - right now the update doesn't work with these changes. Can you update your stored procedure?
> Added Validation to Update - Removed Confirm Email/Password

- Open-Shift/Models/Database.cs
**removed password related fields from update_user
**cleaned up insert_user, made password token and authorixation fields empty strings as default since we dont need them here
> Updates to update_user proc

- Open-Shift/Open-Shift.csproj
- Open-Shift/Scripts/calendar.js
- Open-Shift/Scripts/database.js
- Open-Shift/Scripts/dom-elements.js
- Open-Shift/ViewModels/ScheduleViewModel.cs
- Open-Shift/Views/Profile/Update.cshtml
Started working on scheduling and fixed the profile updating cancel button bug
> Started working on scheduling and fixed a bug

- Open-Shift/Models/Database.cs
- Open-Shift/Scripts/dom-elements.js
Fixed allowing users to update their availabilities
> Fixed allowing users to update their availabilities

- Open-Shift/Controllers/MainController.cs
- Open-Shift/Controllers/ScheduleController.cs
- Open-Shift/Models/Database.cs
- Open-Shift/Models/Shift.cs
- Open-Shift/NOTES.txt
- Open-Shift/Open-Shift.csproj
- Open-Shift/Scripts/availability-script.js
- Open-Shift/Scripts/calendar.js
- Open-Shift/Scripts/database.js
- Open-Shift/Scripts/dom-elements.js
- Open-Shift/Scripts/schedule-script.js
- Open-Shift/ViewModels/ScheduleViewModel.cs
- Open-Shift/Views/Schedule/Index.cshtml
Worked on schedule and availability, added TODO item for Annie (SEE NOTES.txt)
> Worked on schedule and availability, added TODO item for Annie (SEE NOTES.txt)

- Open-Shift/Models/Database.cs
Added strEmailVerificationToken to the database
> Added strEmailVerificationToken to the database

- Open-Shift/Content/Site.css
- Open-Shift/Views/Availability/Index.cshtml
- Open-Shift/Views/Profile/Index.cshtml
- Open-Shift/Views/Profile/SignIn.cshtml
- Open-Shift/Views/Profile/SignUp.cshtml
- Open-Shift/Views/Profile/Update.cshtml
- Open-Shift/Views/Schedule/Index.cshtml
- Open-Shift/Views/Shared/UserLayout.cshtml
Started redesigning. With bootstrap we can easily try different themes later, which will affect the colors, fonts, padding, etc... on all pages.
> Started redesigning

- Open-Shift/Content/Site.css
- Open-Shift/Controllers/HomeController.cs
- Open-Shift/Models/Database.cs
- Open-Shift/Models/Store.cs
- Open-Shift/Open-Shift.csproj
- Open-Shift/ViewModels/HomeViewModel.cs
- Open-Shift/Views/Home/Index.cshtml
- Open-Shift/Views/Profile/Update.cshtml
- Open-Shift/Views/Shared/UserLayout.cshtml
Started working on store management (important database change)
> Started working on store management (important database change)

- Open-Shift/App_Log/sys_log.xls
- Open-Shift/Models/Store.cs
Fixed Home error (important database change)
> Fixed Home error (important database change)

- Open-Shift/Views/Home/Index.cshtml
Added Google Map on the Home page (important database changes)
> Added Google Map on the Home page (important database changes)

- Open-Shift/Models/Database.cs
- Open-Shift/Models/User.cs
- Open-Shift/NOTES.txt
- Open-Shift/Views/Home/Index.cshtml
Added associates to the store list on Home page (important database changes)
> Added associates to the store list on Home page (important database changes)

- Open-Shift/Controllers/EmailController.cs
- Open-Shift/Controllers/Profile.cs
- Open-Shift/Controllers/VerificationController.cs
- Open-Shift/Models/Database.cs
still need to add manager emails
> Working on Manager approving new signup

- Open-Shift/Controllers/Profile.cs
- Open-Shift/Models/Home.cs
- Open-Shift/NOTES.txt
- Open-Shift/Views/Home/Index.cshtml
- Open-Shift/Views/Profile/SignIn.cshtml
Added access restriction based on email verification status
> Added access restriction based on email verification status

- Open-Shift/Controllers/EmailController.cs
- Open-Shift/Controllers/VerificationController.cs
- Open-Shift/Models/Database.cs
associate clicks sign up -> associate gets email with link -> associate clicks link -> manager(s) get emailed with confirmation of associate with their info/database removes emailverification string ->manager clicks link -> database gets updated with intStatusID changing to 1 -> associate can now log in (still need to send a confirmation email)
> Associate signup email fuctionality is complete with this push

- Open-Shift/App_Log/sys_log.xls
- Open-Shift/Controllers/Profile.cs
Added a validation message informing the user that their account is awaiting verification when they sign up or login.
> Account verification validation

- Open-Shift/Open-Shift.csproj
This change allows me to push the app and adjust to any server platformTarget
> Changing Platform Target to build on AnyCPU

- Open-Shift/App_Log/sys_log.xls
- Open-Shift/Content/Site.css
- Open-Shift/Content/calendar.css
- Open-Shift/Controllers/AvailabilityController.cs
- Open-Shift/Controllers/EmailController.cs
- Open-Shift/Controllers/ManagerController.cs
- Open-Shift/Controllers/Profile.cs
- Open-Shift/Controllers/VerificationController.cs
- Open-Shift/Models/Database.cs
- Open-Shift/Models/SystemList.cs
- Open-Shift/Models/User.cs
- Open-Shift/Open-Shift.csproj
- Open-Shift/Scripts/calendar.js
- Open-Shift/Scripts/database.js
- Open-Shift/Scripts/dom-elements.js
- Open-Shift/Views/Availability/Index.cshtml
- Open-Shift/Views/Home/Index.cshtml
- Open-Shift/Views/Profile/Index.cshtml
- Open-Shift/Views/Profile/ResetPassword.cshtml
- Open-Shift/Views/Profile/ResetPasswordRequest.cshtml
- Open-Shift/Views/Profile/SignIn.cshtml
- Open-Shift/Views/Profile/SignUp.cshtml
- Open-Shift/Views/Profile/Update.cshtml
- Open-Shift/Views/Schedule/Index.cshtml
- Open-Shift/Views/Shared/UserLayout.cshtml
Wrapping up features, fixing bugs, adding small features
> Wrapping up features, fixing bugs, adding small features

- Open-Shift/App_Log/sys_log.xls
- Open-Shift/Content/Site.css
- Open-Shift/Content/calendar.css
- Open-Shift/NOTES.txt
- Open-Shift/Scripts/calendar.js
- Open-Shift/Scripts/database.js
> Wrapping up

- Open-Shift/Models/Database.cs
Added error logging everywhere in Database.cs
> Added error logging everywhere in Database.cs

- Open-Shift/Models/User.cs
Added more error logging in User.cs
> Added more error logging in User.cs

- Open-Shift/App_Log/sys_log.xls
- Open-Shift/Content/calendar.css
- Open-Shift/Controllers/EmailController.cs
- Open-Shift/Controllers/Profile.cs
- Open-Shift/Controllers/VerificationController.cs
- Open-Shift/Models/Database.cs
- Open-Shift/Models/SysLog.cs
- Open-Shift/Models/SystemList.cs
- Open-Shift/Models/User.cs
- Open-Shift/NOTES.txt
- Open-Shift/Open-Shift.csproj.user
- Open-Shift/Properties/PublishProfiles/Open-Shift20191212043545 - Web Deploy.pubxml
- Open-Shift/Properties/PublishProfiles/Open-Shift20191212043545 - Web Deploy.pubxml.user
- Open-Shift/Scripts/Utilities.js
- Open-Shift/Scripts/calendar.js
- Open-Shift/Views/Home/Index.cshtml
- Open-Shift/Views/Profile/Index.cshtml
- Open-Shift/Views/Profile/SignIn.cshtml
- Open-Shift/Web.config
> Fixed a bunch of bugs
